/*
 * DBeaver - Universal Database Manager
 * Copyright (C) 2010-2026 DBeaver Corp and others
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.jkiss.dbeaver.ext.weaviate.model;

import org.jkiss.code.NotNull;
import org.jkiss.code.Nullable;
import org.jkiss.dbeaver.model.DBPDataKind;
import org.jkiss.dbeaver.model.DBPDataSource;
import org.jkiss.dbeaver.model.struct.DBSEntity;
import org.jkiss.dbeaver.model.struct.DBSEntityAttribute;
import org.jkiss.dbeaver.model.struct.DBSObject;

/**
 * The server-assigned object id, exposed as a real attribute of the collection.
 * <p>
 * It is not one of the collection's declared properties, but it is a genuine column of every
 * result and the only thing that identifies a row. Modelling it as an attribute -- rather than a
 * ROWID pseudo-attribute -- keeps it visible in the grid: DBeaver hides pseudo-attributes by
 * default ({@code DBDAttributeConstraint#isVisibleByDefault}), which would take the id away from
 * the very view people use to read and copy it.
 *
 * @see WeaviateUuidConstraint the primary key over this attribute, which makes row deletion work
 */
public class WeaviateUuidAttribute implements DBSEntityAttribute {

    private final WeaviateCollection collection;

    public WeaviateUuidAttribute(@NotNull WeaviateCollection collection) {
        this.collection = collection;
    }

    @NotNull
    @Override
    public String getName() {
        return WeaviateColumns.UUID;
    }

    @Override
    public int getOrdinalPosition() {
        return 0;
    }

    @NotNull
    @Override
    public String getTypeName() {
        return "uuid";
    }

    @NotNull
    @Override
    public DBPDataKind getDataKind() {
        return DBPDataKind.STRING;
    }

    @Override
    public long getMaxLength() {
        // Canonical 8-4-4-4-12 form.
        return 36;
    }

    @Override
    public boolean isRequired() {
        return true;
    }

    @Override
    public boolean isAutoGenerated() {
        // Assigned by the server when the object is created.
        return true;
    }

    @Nullable
    @Override
    public String getDefaultValue() {
        return null;
    }

    @Nullable
    @Override
    public Integer getScale() {
        return null;
    }

    @Nullable
    @Override
    public Integer getPrecision() {
        return null;
    }

    @NotNull
    @Override
    public String getFullTypeName() {
        return getTypeName();
    }

    @Override
    public long getTypeModifiers() {
        return 0;
    }

    @Override
    public int getTypeID() {
        return java.sql.Types.VARCHAR;
    }

    @Nullable
    @Override
    public String getDescription() {
        return "Weaviate object ID";
    }

    @NotNull
    @Override
    public DBSEntity getParentObject() {
        return collection;
    }

    @NotNull
    @Override
    public DBPDataSource getDataSource() {
        return collection.getDataSource();
    }

    @Override
    public boolean isPersisted() {
        return true;
    }

    @Override
    public boolean equals(Object obj) {
        return obj instanceof WeaviateUuidAttribute other
            && other.collection == this.collection;
    }

    @Override
    public int hashCode() {
        return collection.hashCode() * 31 + WeaviateColumns.UUID.hashCode();
    }

    @Nullable
    public DBSObject getParent() {
        return collection;
    }
}
