/*
 * DBeaver - Universal Database Manager
 * Copyright (C) 2010-2026 DBeaver Corp and others
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.jkiss.dbeaver.ext.weaviate.model;

import io.weaviate.client6.v1.api.collections.DataType;
import io.weaviate.client6.v1.api.collections.Property;
import org.jkiss.code.NotNull;
import org.jkiss.code.Nullable;
import org.jkiss.dbeaver.model.DBPDataKind;
import org.jkiss.dbeaver.model.DBPDataSource;
import org.jkiss.dbeaver.model.struct.DBSEntity;
import org.jkiss.dbeaver.model.struct.DBSEntityAttribute;

import java.util.List;

public class WeaviateProperty implements DBSEntityAttribute {

    private final WeaviateCollection collection;
    private final Property property;
    private final int ordinalPosition;

    public WeaviateProperty(
        @NotNull WeaviateCollection collection,
        @NotNull Property property,
        int ordinalPosition
    ) {
        this.collection = collection;
        this.property = property;
        this.ordinalPosition = ordinalPosition;
    }

    @NotNull
    @Override
    @org.jkiss.dbeaver.model.meta.Property(viewable = true, order = 1)
    public String getName() {
        return property.propertyName();
    }

    @Nullable
    @Override
    @org.jkiss.dbeaver.model.meta.Property(viewable = true, order = 2)
    public String getDescription() {
        return property.description();
    }

    @NotNull
    @Override
    @org.jkiss.dbeaver.model.meta.Property(viewable = true, order = 3)
    public String getTypeName() {
        List<String> dataTypes = property.dataTypes();
        if (dataTypes == null || dataTypes.isEmpty()) {
            return "unknown";
        }
        return String.join("|", dataTypes);
    }

    @NotNull
    @Override
    public String getFullTypeName() {
        return getTypeName();
    }

    @Override
    public int getTypeID() {
        return 0;
    }

    @NotNull
    @Override
    public DBPDataKind getDataKind() {
        List<String> dataTypes = property.dataTypes();
        if (dataTypes == null || dataTypes.isEmpty()) {
            return DBPDataKind.UNKNOWN;
        }
        return mapDataKind(dataTypes.get(0));
    }

    @NotNull
    public static DBPDataKind mapDataKind(@NotNull String weaviateType) {
        switch (weaviateType) {
            case DataType.TEXT:
            case DataType.TEXT_ARRAY:
            case DataType.UUID:
            case DataType.UUID_ARRAY:
            case DataType.PHONE_NUMBER:
                return DBPDataKind.STRING;
            case DataType.INT:
            case DataType.INT_ARRAY:
            case DataType.NUMBER:
            case DataType.NUMBER_ARRAY:
                return DBPDataKind.NUMERIC;
            case DataType.BOOL:
            case DataType.BOOL_ARRAY:
                return DBPDataKind.BOOLEAN;
            case DataType.DATE:
            case DataType.DATE_ARRAY:
                return DBPDataKind.DATETIME;
            case DataType.BLOB:
                return DBPDataKind.BINARY;
            case DataType.GEO_COORDINATES:
            case DataType.OBJECT:
            case DataType.OBJECT_ARRAY:
                return DBPDataKind.OBJECT;
            default:
                // cross-references to other collections
                return DBPDataKind.OBJECT;
        }
    }

    @Nullable
    @Override
    public Integer getScale() {
        return null;
    }

    @Nullable
    @Override
    public Integer getPrecision() {
        return null;
    }

    @Override
    public long getMaxLength() {
        return 0;
    }

    @Override
    public long getTypeModifiers() {
        return 0;
    }

    @Override
    public boolean isRequired() {
        return false;
    }

    @Override
    public boolean isAutoGenerated() {
        return false;
    }

    @Override
    public int getOrdinalPosition() {
        return ordinalPosition;
    }

    @Nullable
    @Override
    public String getDefaultValue() {
        return null;
    }

    @NotNull
    @Override
    public DBSEntity getParentObject() {
        return collection;
    }

    @NotNull
    @Override
    public DBPDataSource getDataSource() {
        return collection.getDataSource();
    }

    @Override
    public boolean isPersisted() {
        return true;
    }
}
